[project]
name = "blogapp"
version = "0.1.0"
description = "sample blog crud application using fastapi"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "sqlalchemy>=2.0.46",
]
